CompileFlags: 
  Add: [-Wall, -Wextra, -pedantic, -I, ../include/, -I, ./include/]
  Compiler: gcc   

---
# C++ Files
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add:
    - "-std=c++20"
  Compiler: g++
