live_config_reload = true


[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x41505e"
blue = "0x5ec4ff"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xe27e8d"
red = "0xd95468"
white = "0xffffff"
yellow = "0xebbf83"

[colors.cursor]
cursor = "0x008b94"
text = "0xfafafa"

[colors.normal]
black = "0x333f4a"
blue = "0x539afc"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xb62d65"
red = "0xd95468"
white = "0xb7c5d3"

[colors.primary]
background = "0x171d23"
foreground = "0xffffff"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.9
title = "Alacritty"
dynamic_title = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30
